name: Check Outdated Version Pinning

on:
  schedule:
    - cron: '0 12 * * 1'  # Run at 12:00 UTC every Monday

permissions:
  issues: write
  contents: read

jobs:
  check-pinning-dates:
    runs-on: ubuntu-slim
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Validate JSON Schema
        shell: pwsh
        run: ./helpers/CheckOutdatedVersionPinning.ps1
        env:
          GH_TOKEN: ${{ github.token }}
