# CI Validation

name: PowerShell Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'helpers/software-report-base/**'

jobs:
  powershell-tests:
    name: PowerShell tests
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Run Software Report module tests
        shell: pwsh
        run: |
            $ErrorActionPreference = "Stop"
            Invoke-Pester -Output Detailed "helpers/software-report-base/tests"
        